import SwiftUI

struct PrivacyPolicyView: View {
    @EnvironmentObject var languageManager:LanguageManager
    @Environment(\.colorScheme) private var colorScheme
    var body: some View {
             ZStack{
            colorScheme == .light ?  Color.hex("F2F2F7").ignoresSafeArea(.all):Color("NewBlack1").ignoresSafeArea(.all)
                 ScrollView{
               
            
            VStack(alignment: .leading, spacing: 16) {
//                Text("Privacy Policy")
//                    .font(.largeTitle)
//                    .fontWeight(.bold)
//                    .padding(.bottom, 8)

                Text("Last updated: January 13, 2025".addLocalizableString(str: languageManager.language))
                    .font(.subheadline)
                    .foregroundColor(.gray)

                Group {
                    Text("This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.".addLocalizableString(str: languageManager.language))

                    Text("We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.".addLocalizableString(str: languageManager.language))
                }
                .font(.body)

                Group {
                    Text("Interpretation and Definitions".addLocalizableString(str: languageManager.language))
                        .font(.title2)
                        .fontWeight(.semibold)
                        .padding(.top, 16)

                    Text("Interpretation".addLocalizableString(str: languageManager.language))
                        .font(.headline)
                        .fontWeight(.semibold)

                    Text("The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.".addLocalizableString(str: languageManager.language))
                }

                Group {
                    Text("Definitions".addLocalizableString(str: languageManager.language))
                        .font(.headline)
                        .fontWeight(.semibold)
                        .padding(.top, 8)

                    Text("For the purposes of this Privacy Policy:".addLocalizableString(str: languageManager.language))

                    Text("- **Account** means a unique account created for You to access our Service or parts of our Service.".addLocalizableString(str: languageManager.language))

                    Text("- **Affiliate** means an entity that controls, is controlled by or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.".addLocalizableString(str: languageManager.language))

                    Text("- **Application** refers to Map Mate-AI, the software program provided by the Company.".addLocalizableString(str: languageManager.language))

                    Text("- **Company** (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to Map Mate-AI.".addLocalizableString(str: languageManager.language))

                    Text("- **Country** refers to: Turkey.".addLocalizableString(str: languageManager.language))

                    Text("- **Device** means any device that can access the Service such as a computer, a cellphone or a digital tablet.".addLocalizableString(str: languageManager.language))

                    Text("- **Personal Data** is any information that relates to an identified or identifiable individual.".addLocalizableString(str: languageManager.language))

                    Text("- **Service** refers to the Application.".addLocalizableString(str: languageManager.language))

                    Text("- **Service Provider** means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.".addLocalizableString(str: languageManager.language))

                    Text("- **Usage Data** refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).".addLocalizableString(str: languageManager.language))

                    Text("- **You** means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.".addLocalizableString(str: languageManager.language))
                }
                .padding(.bottom, 8)

                Text("For the complete Privacy Policy, please visit our website or contact us at erkinarikan@gmail.com.".addLocalizableString(str: languageManager.language))
                    .font(.footnote)
                    .foregroundColor(.blue)
            }
           
            .padding()
            }
        }
        .navigationTitle("Privacy Policy".addLocalizableString(str: languageManager.language))
    }
}

struct PrivacyPolicyView_Previews: PreviewProvider {
    static var previews: some View {
        PrivacyPolicyView()
            .environmentObject(LanguageManager())
            
    }
}
